# Generated by Django 4.2.27 on 2025-12-10 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0002_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
