# Generated by Django 4.2.27 on 2025-12-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0005_alter_profile_location_delete_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
